/**
 * @file app_config.h
 * @brief 应用配置定义
 */

#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/* 设备配置 */
#define APP_DEVICE_NAME         CONFIG_MIDI_DEVICE_NAME
#define APP_PRODUCT_ID          CONFIG_MIDI_PRODUCT_ID
#define APP_LISTEN_PORT         CONFIG_MIDI_LISTEN_PORT

/* 任务栈大小 */
#define APP_SESSION_MONITOR_STACK   CONFIG_MIDI_SESSION_MONITOR_STACK
#define APP_EVENT_HANDLER_STACK     CONFIG_MIDI_EVENT_HANDLER_STACK

/* 任务优先级 */
#define APP_SESSION_MONITOR_PRIORITY    CONFIG_MIDI_SESSION_MONITOR_PRIORITY
#define APP_EVENT_HANDLER_PRIORITY      CONFIG_MIDI_EVENT_HANDLER_PRIORITY

/* 定时配置 */
#define APP_SESSION_CHECK_INTERVAL_MS   CONFIG_MIDI_SESSION_CHECK_INTERVAL

#endif // APP_CONFIG_H