; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3usbotg]
platform = espressif32
board = esp32s3usbotg
framework = espidf

monitor_speed = 115200

; 方式1：在这里直接写 WiFi 账号密码（推荐只在本地用，不要提交到公共仓库）
; build_flags =
;   -DWIFI_SSID=\"YourSSID\"
;   -DWIFI_PASS=\"YourPassword\"